cxx_binary(
  name = 'test',
  header_namespace = '',
  headers = {
    'test/catch.hpp': 'catch.hpp',
  },
  srcs = glob([
    '**/*.cpp',
  ]),
  compiler_flags = [
    '-std=c++11',
  ],
  deps = [
    '//:fuzzylite',
  ],
)
